# Feature 4 — AI Runbook Generator
# Converts raw incident notes into formatted runbooks
# Auto-commits the runbook to the repo

import os
import sys
from datetime import datetime

def generate_runbook(incident_notes: str) -> str:
    """Generate a formatted runbook from raw incident notes."""
    
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    
    if api_key and api_key.startswith("sk-ant-"):
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=api_key)
            prompt = (
                "You are a senior DevOps engineer writing a post-incident runbook.\n"
                "Convert these raw incident notes into a professional runbook.\n\n"
                "Format as:\n"
                "# Incident Runbook — [Title]\n"
                "## Summary\n"
                "## Impact\n"
                "## Timeline\n"
                "## Root Cause\n"
                "## Resolution Steps\n"
                "## Prevention\n"
                "## Lessons Learned\n\n"
                "Raw notes:\n" + incident_notes
            )
            message = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=1500,
                messages=[{"role": "user", "content": prompt}]
            )
            return message.content[0].text
        except Exception as e:
            print(f"API call failed ({e}), using mock response\n")
            return get_mock_runbook(incident_notes)
    else:
        print("No API key found, using mock response\n")
        return get_mock_runbook(incident_notes)


def get_mock_runbook(incident_notes: str) -> str:
    """Mock runbook for testing without API credits."""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date = datetime.now().strftime("%Y-%m-%d")
    
    runbook = f"""# Incident Runbook — Pipeline/Infrastructure Failure
*Generated: {timestamp} by AI DevOps Platform*
*(Mock response — add API credits for live Claude generation)*

---

## Summary
Infrastructure incident detected and resolved by the on-call DevOps team.
Incident was identified through monitoring alerts and resolved within SLA.

## Impact
- Affected services: Production pipeline / Infrastructure deployment
- Duration: Under investigation
- Users affected: Engineering team
- Severity: P2

## Timeline
| Time | Event |
|------|-------|
| T+0  | Incident detected via monitoring alert |
| T+5  | On-call engineer paged and acknowledged |
| T+15 | Root cause identified |
| T+30 | Fix applied and services restored |
| T+45 | Post-incident review initiated |

## Root Cause
Based on incident notes:
{incident_notes[:300]}...

The root cause was identified as an infrastructure configuration issue
that caused service disruption. Full RCA to be completed within 24 hours.

## Resolution Steps
1. Acknowledged alert and assembled response team
2. Identified affected resources in Azure portal
3. Investigated logs in Azure Monitor and Log Analytics
4. Applied fix — see incident notes for specific steps taken
5. Verified services restored via health checks
6. Notified stakeholders of resolution

## Prevention
- Add monitoring alerts for early detection of this failure pattern
- Update runbook with specific fix steps
- Review infrastructure configuration in next sprint
- Consider adding automated remediation for this failure type
- Schedule team review of related systems

## Lessons Learned
- Early detection through monitoring reduced impact significantly
- Runbook documentation needs to be kept up to date
- Consider adding this scenario to chaos engineering tests
- Communication to stakeholders could be improved

## References
- Azure Monitor: https://portal.azure.com
- GitHub Actions: https://github.com/amithvr46/ai-devops-platform/actions
- Terraform State: Check backend storage account

---
*Runbook generated by AI DevOps Platform | github.com/amithvr46/ai-devops-platform*
"""
    return runbook


def save_runbook(runbook: str, title: str) -> str:
    """Save runbook to the runbooks folder."""
    
    # Create runbooks directory if it doesn't exist
    os.makedirs("runbooks", exist_ok=True)
    
    # Generate filename from date and title
    date = datetime.now().strftime("%Y-%m-%d")
    safe_title = title.lower().replace(" ", "-").replace("/", "-")[:30]
    filename = f"runbooks/{date}-{safe_title}.md"
    
    with open(filename, 'w') as f:
        f.write(runbook)
    
    return filename


def main():
    print("=" * 60)
    print("AI Runbook Generator")
    print("=" * 60)
    
    if len(sys.argv) > 1:
        # Read from file
        notes_file = sys.argv[1]
        try:
            with open(notes_file, 'r') as f:
                incident_notes = f.read()
            print(f"Reading incident notes from: {notes_file}\n")
        except FileNotFoundError:
            print(f"File not found: {notes_file}")
            sys.exit(1)
    else:
        # Use sample incident for demo
        print("No notes file provided — using sample incident\n")
        incident_notes = """
AKS deployment failed at 2:30pm
Pipeline showed node scheduling errors
Pods stuck in pending state for 20 mins
Found node pool was at max capacity (3/3 nodes)
Manually scaled node pool to 5 nodes in Azure portal
Pods started scheduling after 5 mins
All services restored by 3:15pm
Root cause: autoscaler was disabled on node pool
Fix: re-enabled autoscaler, set max to 8 nodes
About 45 mins of degraded performance
Dev and staging teams affected
No data loss
"""

    # Get title for the runbook
    if len(sys.argv) > 2:
        title = " ".join(sys.argv[2:])
    else:
        title = "infrastructure-incident"

    print("Generating runbook...\n")
    runbook = generate_runbook(incident_notes)
    
    # Save to runbooks folder
    filename = save_runbook(runbook, title)
    
    print("=" * 60)
    print(runbook)
    print("=" * 60)
    print(f"\nRunbook saved to: {filename}")
    print("Commit this file to GitHub to keep a record of all incidents")


if __name__ == "__main__":
    main()